version: '3'

tasks:
  install:
    cmds:
      - bun add -g prettier
      - bun install

  drizzle:
    cmds:
      - bunx drizzle-kit pull --config db/drizzle.config.ts

  lint:
    cmds:
      - prettier --write .

  dev:
    cmds:
      - bun run cmd/main.ts

  serve:
    cmds:
      - bun run cmd/serve.ts
    env:
      PORT: 4000

  mysql:
    cmds:
      - bun run cmd/mysql.ts
    env:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
