version: '3'

tasks:
  install:
    cmds:
      - npm i -g prettier
      - bun install

  lint:
    cmds:
      - prettier --write .

  dev:
    cmds:
      - bun run cmd/main.ts

  mysql:
    cmds:
      - bun run cmd/mysql.ts
