version: '3'

tasks:
  install:
    cmds:
      - bun add -g prettier
      - bun install

  drizzle:
    cmds:
      - bunx drizzle-kit pull --config db/drizzle.config.ts

  lint:
    cmds:
      - prettier --write .

  compose:
    cmds:
      - docker compose -f compose.yaml up -d

  dev:
    cmds:
      - bun run cmd/main.ts
    env:
      PORT: 4001
      JWT_SECRET: secret
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: demo
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_USERNAME: root
      REDIS_PASSWORD: 1234
      REDIS_DATABASE: 0

  build:
    cmds:
      - |
        bun build \
        --compile \
        --minify-whitespace \
        --minify-syntax \
        --target=bun-darwin-arm64 \
        --outfile bin/app \
        ./cmd/main.ts

  mysql:
    cmds:
      - bun run cmd/mysql.ts
    env:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo

  redis:
    cmds:
      - bun run cmd/redis.ts
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_USERNAME: root
      REDIS_PASSWORD: 1234
      REDIS_DATABASE: 0
