version: '3'

tasks:
  install:
    cmds:
      - bun add -g prettier
      - bun install

  drizzle:
    cmds:
      - bunx drizzle-kit pull --config db/drizzle.config.ts

  lint:
    cmds:
      - prettier --write .

  dev:
    cmds:
      - bun run cmd/main.ts

  mysql:
    cmds:
      - bun run cmd/mysql.ts
